create database postgres
    with owner cadastro;

comment on database postgres is 'default administrative connection database';

create sequence public.hibernate_sequence;

alter sequence public.hibernate_sequence owner to cadastro;

create table public.restaurante
(
  id              bigint generated by default as identity
    primary key,
  latitude        double precision,
  longitude       double precision,
  cnpj            varchar(255),
  dataatualizacao date,
  datacriacao     date,
  nome            varchar(255),
  proprietario    varchar(255),
  localizacao_id  bigint
    constraint fk68yo0607f7esp4vjljpg4e2u0
      references public.restaurante
    constraint fk_restaurante_on_localizacao
      references public.restaurante
);

alter table public.restaurante
  owner to cadastro;

create table public.prato
(
  id             bigint not null
    primary key,
  descricao      varchar(255),
  nome           varchar(255),
  preco          numeric(19, 2),
  restaurante_id bigint
    constraint fk43yo4ddilkvn6ebgfcx2vnqs7
      references public.restaurante
    constraint fk_prato_on_restaurante
      references public.restaurante
);

alter table public.prato
  owner to cadastro;

create table public.localizacao
(
  id        bigint generated by default as identity
    constraint pk_localizacao
      primary key,
  latitude  double precision,
  longitude double precision
);

alter table public.localizacao
  owner to cadastro;

